/**
 * Browseable directory of leagues for the homepage. Each entry is one sport's
 * competition running over a fixed window — a "league" here means a season
 * or tournament, not a single game. This is presentational data only; the
 * only entry actually wired to the trading engine is World Cup 2026
 * (src/lib/game/store.ts, code WC2026). Everything else is browse-only for
 * the demo.
 */

export interface LeagueSummary {
  id: string;
  sport: string;
  name: string;
  emoji: string;
  status: "live" | "upcoming" | "in season";
  windowLabel: string;
  traders: number;
  buyInReal: number;
  buyInFake: number;
  joined: boolean;
  blurb: string;
  /** Present only for the one league actually playable in this demo. */
  code?: string;
}

export const LEAGUE_CATALOG: LeagueSummary[] = [
  {
    id: "world-cup-2026",
    sport: "World Cup",
    name: "World Cup 2026",
    emoji: "🏆",
    status: "live",
    windowLabel: "Jun 11 – Jul 19, 2026",
    traders: 11,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: true,
    code: "WC2026",
    blurb: "Final matchday — FC Falcon vs United Wolves is live right now. You're in this one.",
  },
  {
    id: "afl-premiership",
    sport: "AFL",
    name: "AFL Premiership",
    emoji: "🏉",
    status: "in season",
    windowLabel: "Mar – Sep 2026",
    traders: 342,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "Australian Football League season-long market — 18 clubs, one grand final.",
  },
  {
    id: "mlb",
    sport: "Baseball",
    name: "MLB",
    emoji: "⚾",
    status: "in season",
    windowLabel: "Mar – Oct 2026",
    traders: 918,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "162-game grind — pitching rotations and streak trades all summer.",
  },
  {
    id: "npb",
    sport: "Baseball",
    name: "NPB (Japan)",
    emoji: "⚾",
    status: "in season",
    windowLabel: "Mar – Oct 2026",
    traders: 176,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "Nippon Professional Baseball — Central and Pacific League markets.",
  },
  {
    id: "kbo",
    sport: "Baseball",
    name: "KBO League (Korea)",
    emoji: "⚾",
    status: "in season",
    windowLabel: "Apr – Oct 2026",
    traders: 121,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "Korea Baseball Organization — 10 clubs, wild-card October.",
  },
  {
    id: "euroleague",
    sport: "Basketball",
    name: "EuroLeague",
    emoji: "🏀",
    status: "in season",
    windowLabel: "Oct 2025 – May 2026",
    traders: 264,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "Europe's top club competition — Final Four odds move all season.",
  },
  {
    id: "march-madness",
    sport: "Basketball",
    name: "NCAA March Madness",
    emoji: "🏀",
    status: "upcoming",
    windowLabel: "Mar 2026",
    traders: 601,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "Single-elimination bracket chaos — a three-week sprint, not a season.",
  },
  {
    id: "premier-league",
    sport: "Football",
    name: "Premier League",
    emoji: "⚽",
    status: "in season",
    windowLabel: "Aug 2025 – May 2026",
    traders: 843,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "England's top flight — 38 matchdays, title race down to the wire.",
  },
  {
    id: "la-liga",
    sport: "Football",
    name: "La Liga",
    emoji: "⚽",
    status: "in season",
    windowLabel: "Aug 2025 – May 2026",
    traders: 512,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "Spain's top division — technical, tight, and title-contested top to bottom.",
  },
  {
    id: "ucl",
    sport: "Football",
    name: "UEFA Champions League",
    emoji: "⚽",
    status: "in season",
    windowLabel: "Sep 2025 – May 2026",
    traders: 729,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "Europe's premier club competition — knockout markets swing hard.",
  },
  {
    id: "f1",
    sport: "Formula-1",
    name: "F1 World Championship",
    emoji: "🏎️",
    status: "in season",
    windowLabel: "Mar – Dec 2026",
    traders: 388,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "24-race calendar — constructor and driver markets move every quali.",
  },
  {
    id: "ehf-champions-league",
    sport: "Handball",
    name: "EHF Champions League",
    emoji: "🤾",
    status: "in season",
    windowLabel: "Sep 2025 – Jun 2026",
    traders: 94,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "European club handball's top tier — fast breaks, faster price swings.",
  },
  {
    id: "nhl",
    sport: "Hockey",
    name: "NHL",
    emoji: "🏒",
    status: "in season",
    windowLabel: "Oct 2025 – Jun 2026",
    traders: 447,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "82 games to the playoffs, then a two-month Cup run.",
  },
  {
    id: "iihf-worlds",
    sport: "Hockey",
    name: "IIHF World Championship",
    emoji: "🏒",
    status: "upcoming",
    windowLabel: "May 2026",
    traders: 133,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "National-team hockey — a compact, high-variance two-week window.",
  },
  {
    id: "ufc",
    sport: "MMA",
    name: "UFC",
    emoji: "🥊",
    status: "live",
    windowLabel: "Year-round",
    traders: 356,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "Event-by-event markets — one fight card open right now.",
  },
  {
    id: "nba",
    sport: "NBA",
    name: "NBA 2025–26",
    emoji: "🏀",
    status: "in season",
    windowLabel: "Oct 2025 – Jun 2026",
    traders: 1024,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "82 games, in-season tournament, and a long playoff tail.",
  },
  {
    id: "nfl",
    sport: "NFL",
    name: "NFL 2025–26",
    emoji: "🏈",
    status: "in season",
    windowLabel: "Sep 2025 – Feb 2026",
    traders: 1187,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "17-week regular season sprinting into a single-elimination bracket.",
  },
  {
    id: "six-nations",
    sport: "Rugby",
    name: "Six Nations Championship",
    emoji: "🏉",
    status: "upcoming",
    windowLabel: "Feb – Mar 2026",
    traders: 158,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "Europe's rugby championship — five rounds, one Grand Slam shot.",
  },
  {
    id: "rugby-world-cup",
    sport: "Rugby",
    name: "Rugby World Cup",
    emoji: "🏉",
    status: "upcoming",
    windowLabel: "Sep – Oct 2027",
    traders: 89,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "The next cycle's qualifiers are already moving markets.",
  },
  {
    id: "fivb-vnl",
    sport: "Volleyball",
    name: "FIVB Volleyball Nations League",
    emoji: "🏐",
    status: "in season",
    windowLabel: "May – Jul 2026",
    traders: 112,
    buyInReal: 10,
    buyInFake: 1_000_000,
    joined: false,
    blurb: "National-team volleyball round-robin building to Finals week.",
  },
];
